// ═══════════════════════════════════════
// FAMILIES
// ═══════════════════════════════════════
var F={
lifemaker:{n:"Life Makers",c:"#66BB6A",bg:"rgba(102,187,106,.08)",gl:"rgba(102,187,106,.3)",bd:"rgba(102,187,106,.2)",bio:"These are the building blocks of everything alive. You, me, trees, {toy}. They make life possible.",disc:"Life energy flows through me!",audio:[440,'sine',.12]},
noble:{n:"Glow Squad",c:"#CE93D8",bg:"rgba(206,147,216,.08)",gl:"rgba(206,147,216,.3)",bd:"rgba(206,147,216,.2)",bio:"The lone wolves of my kingdom. They never team up with anyone. But send electricity through them and they glow any color you want.",disc:"My wings shimmer with new light!",audio:[880,'sine',.18]},
warrior:{n:"Metal Warriors",c:"#5C6BC0",bg:"rgba(92,107,192,.08)",gl:"rgba(92,107,192,.3)",bd:"rgba(92,107,192,.2)",bio:"My biggest army! These metals build everything. Bridges, coins, jewelry, rockets. The workhorses of the world.",disc:"My armor hardens! Nothing can stop me!",audio:[330,'triangle',.1]},
explosion:{n:"Explosion Squad",c:"#EF5350",bg:"rgba(239,83,80,.08)",gl:"rgba(239,83,80,.3)",bd:"rgba(239,83,80,.2)",bio:"CAREFUL, {name}! Drop these in water and BOOM! The most wild and reactive metals. Dangerous, powerful, and never boring.",disc:"POWER surges through my veins!",audio:[200,'square',.06]},
earth:{n:"Earth Builders",c:"#FFA726",bg:"rgba(255,167,38,.08)",gl:"rgba(255,167,38,.3)",bd:"rgba(255,167,38,.2)",bio:"Strong and steady like the ground beneath your feet. They build bones, make fireworks flash, and chalk the sidewalk.",disc:"The ground trembles with new strength!",audio:[260,'sine',.14]},
shifter:{n:"Shape Shifters",c:"#26A69A",bg:"rgba(38,166,154,.08)",gl:"rgba(38,166,154,.3)",bd:"rgba(38,166,154,.2)",bio:"Sneaky metals that bend and change. Some melt right in your hand! Soft but very clever.",disc:"My form shifts and flows!",audio:[500,'sine',.1]},
halfhalf:{n:"Half-and-Halfs",c:"#AB47BC",bg:"rgba(171,71,188,.08)",gl:"rgba(171,71,188,.3)",bd:"rgba(171,71,188,.2)",bio:"The tricksters! Half metal, half not. Silicon is beach sand that learned to think. They cannot pick a side.",disc:"Both sides of my power unite!",audio:[600,'triangle',.12]},
saltmaker:{n:"Salt Makers",c:"#C0CA33",bg:"rgba(192,202,51,.08)",gl:"rgba(192,202,51,.3)",bd:"rgba(192,202,51,.2)",bio:"Fierce and stinky! These make salts, clean pools, and protect teeth. They fight germs and never apologize for the smell.",disc:"My breath burns with fierce energy!",audio:[700,'sawtooth',.06]},
hidden:{n:"Hidden Powers",c:"#00897B",bg:"rgba(0,137,123,.08)",gl:"rgba(0,137,123,.3)",bd:"rgba(0,137,123,.2)",bio:"My secret weapons! Rare earths hiding inside every phone, every magnet, every laser. The world runs on them.",disc:"Ancient secrets awaken inside me!",audio:[520,'sine',.16]},
radioactive:{n:"Radioactive Force",c:"#FF7043",bg:"rgba(255,112,67,.08)",gl:"rgba(255,112,67,.3)",bd:"rgba(255,112,67,.2)",bio:"The final bosses. Planet-level power. Uranium runs whole cities. Plutonium could destroy them. The most powerful elements in existence.",disc:"Raw cosmic power floods through me!",audio:[180,'square',.08]}
};

// ═══════════════════════════════════════
// ELEMENT DATA (all 118)
// ═══════════════════════════════════════
var E=[
// L1: 20 starters (combos, revisit lines, rich stories)
{n:"Hydrogen",s:"H",num:1,e:"💧",f:"lifemaker",p:"Tiny powerhouse",fact:"Lightest thing in the universe!",story:"I'm tiny but mighty. Two of me plus Oxygen makes every drop of water {name} drinks.",l1:1,eLine:"The first atom ever born! Ancient fire returns!",rv:"Back so soon? I may be tiny but I'm unforgettable!",cb:[{w:"Oxygen",r:"Water 💧",eq:"H₂O"},{w:"Hydrogen",r:"Hydrogen Gas 🫧",eq:"H₂"}]},
{n:"Helium",s:"He",num:2,e:"🎈",f:"noble",p:"Floaty giggler",fact:"I make balloons fly!",story:"WHEEE! Breathe me in and your voice goes all squeaky! I float above everything!",l1:1,eLine:"My wings feel lighter already!",rv:"WHEEE you're back! Want to float with me again?",cb:[]},
{n:"Carbon",s:"C",num:6,e:"💎",f:"lifemaker",p:"Builder of life",fact:"I'm in EVERYTHING alive!",story:"I'm inside {toy}! Cotton is long chains of me, Carbon! Hug {toy} and you hug billions of my atoms.",l1:1,eLine:"I feel {toy}'s warmth! Life energy is flooding back!",rv:"Hey, go hug {toy} for me. I'm in every thread.",cb:[{w:"Oxygen",r:"Carbon Dioxide 🌬️",eq:"CO₂"},{w:"Carbon + heat",r:"Diamond 💎",eq:"C → 💎"},{w:"Hydrogen",r:"Methane 🔥",eq:"CH₄"}]},
{n:"Nitrogen",s:"N",num:7,e:"👻",f:"lifemaker",p:"Invisible ninja",fact:"I'm most of the air!",story:"Can't see me, smell me, or taste me. But almost 8 out of 10 bits of air? That's me. Ninja life.",l1:1,rv:"Shh. I was here the whole time. You just couldn't see me.",cb:[{w:"Hydrogen",r:"Ammonia 🧴",eq:"NH₃"},{w:"Oxygen",r:"Laughing Gas 😂",eq:"N₂O"}]},
{n:"Oxygen",s:"O",num:8,e:"🌬️",f:"lifemaker",p:"Breath of life",fact:"Every breath. That's me.",story:"Breathe in right now, {name}. Feel that? That's me giving your whole body energy. You're welcome.",l1:1,eLine:"I can BREATHE again! *takes huge breath*",rv:"Take a deep breath. That's me saying hello.",cb:[{w:"Hydrogen",r:"Water 💧",eq:"H₂O"},{w:"Iron",r:"Rust 🟤",eq:"Fe₂O₃"},{w:"Carbon",r:"Carbon Dioxide 🌬️",eq:"CO₂"}]},
{n:"Sodium",s:"Na",num:11,e:"🍟",f:"explosion",p:"Salty explosive",fact:"I EXPLODE in water!",story:"On fries I'm yummy salt. Alone near water? BOOM! Stand back!",l1:1,rv:"Keep me away from that water glass. I'm serious.",cb:[{w:"Chlorine",r:"Table Salt 🧂",eq:"NaCl"}]},
{n:"Aluminum",s:"Al",num:13,e:"✈️",f:"shifter",p:"Lightweight champ",fact:"Strong but super light!",story:"Foil, cans, airplane wings. I hold a plane up AND get crushed by your hand. Weird, right?",l1:1,rv:"Crush a foil ball for me. Go on. I can take it.",cb:[{w:"Oxygen",r:"Sapphires! 💙",eq:"Al₂O₃"}]},
{n:"Silicon",s:"Si",num:14,e:"💻",f:"halfhalf",p:"Thinking sand",fact:"Sand that thinks!",story:"Started as beach sand. Now I run every computer, phone, and tablet. Biggest glow up ever.",l1:1,rv:"I'm literally inside the thing you're tapping right now.",cb:[{w:"Oxygen",r:"Glass & Sand 🏖️",eq:"SiO₂"}]},
{n:"Sulfur",s:"S",num:16,e:"🥚",f:"lifemaker",p:"Stinky legend",fact:"I stink. Sorry not sorry.",story:"Rotten egg smell? That's me. I also live in volcanoes. Gross AND awesome.",l1:1,rv:"You came back even though I stink? Respect.",cb:[{w:"Oxygen",r:"Sulfuric Acid ⚗️",eq:"H₂SO₄"},{w:"Iron",r:"Fool's Gold ✨",eq:"FeS₂"}]},
{n:"Chlorine",s:"Cl",num:17,e:"🏊",f:"saltmaker",p:"Pool protector",fact:"I zap germs in water!",story:"That pool smell? Me, fighting germs so {name} can splash safe. Tough job, someone's gotta.",l1:1,rv:"Smell that? Oh wait, you can't. I'm just text. Lucky you.",cb:[{w:"Sodium",r:"Table Salt 🧂",eq:"NaCl"}]},
{n:"Potassium",s:"K",num:19,e:"🍌",f:"explosion",p:"Banana power",fact:"I hide in bananas!",story:"I help muscles move and hearts beat. Next time {name} eats a banana, say hi to me.",l1:1,rv:"Banana time yet? I'll be waiting inside.",cb:[{w:"Water",r:"EXPLOSION! 💥",eq:"2K + H₂O → boom"}]},
{n:"Calcium",s:"Ca",num:20,e:"🦴",f:"earth",p:"Bone builder",fact:"I build your bones!",story:"Without me you'd be floppy like a jellyfish. Every glass of milk makes {name} stronger because of me.",l1:1,rv:"Stand up straight! That's me holding you up.",cb:[{w:"Carbon+Oxygen",r:"Chalk ✏️",eq:"CaCO₃"}]},
{n:"Titanium",s:"Ti",num:22,e:"🦾",f:"warrior",p:"Superhero metal",fact:"Superhero strong!",story:"Rockets, jets, fake bones. Almost nothing breaks me. Superheroes would pick me for armor.",l1:1,rv:"Try to break me. Go ahead. I'll wait.",cb:[{w:"Oxygen",r:"White Paint 🎨",eq:"TiO₂"}]},
{n:"Iron",s:"Fe",num:26,e:"🌉",f:"warrior",p:"Strong protector",fact:"Bridges AND blood!",story:"I hold up bridges outside AND carry oxygen inside {name}'s blood. Double duty. No big deal.",l1:1,rv:"I'm in your blood RIGHT NOW. You literally can't live without me.",cb:[{w:"Carbon",r:"Steel ⚔️",eq:"Fe+C"},{w:"Oxygen",r:"Rust 🟤",eq:"Fe₂O₃"},{w:"Sulfur",r:"Fool's Gold ✨",eq:"FeS₂"}]},
{n:"Nickel",s:"Ni",num:28,e:"🪙",f:"warrior",p:"Coin keeper",fact:"Coins are named after me!",story:"That shiny nickel in the piggy bank? Me. Smooth, strong, and humble about it.",l1:1,rv:"Check your pockets. I might be in there.",cb:[]},
{n:"Copper",s:"Cu",num:29,e:"🟤",f:"warrior",p:"Wire runner",fact:"I carry electricity!",story:"Every light, TV, charger. Electricity flows through me in the walls. I'm the delivery dragon of power.",l1:1,rv:"Turn on a light. That electricity just ran through me.",cb:[{w:"Tin",r:"Bronze 🏺",eq:"Cu+Sn"},{w:"Zinc",r:"Brass 🎺",eq:"Cu+Zn"}]},
{n:"Silver",s:"Ag",num:47,e:"🪞",f:"warrior",p:"Mirror maker",fact:"Shiniest metal ever!",story:"Mirrors? Me. I bounce light so perfectly you see yourself. Pretty cool trick, right?",l1:1,rv:"Look in a mirror. You're seeing me in action.",cb:[{w:"Sulfur",r:"Tarnish 🖤",eq:"Ag₂S"}]},
{n:"Gold",s:"Au",num:79,e:"👑",f:"warrior",p:"The king",fact:"I never rust. Ever.",story:"Pirates hunted me. Queens wore me. I stay shiny for thousands of years. I'm THAT good.",l1:1,eLine:"My scales are hardening into golden armor!",rv:"Back for more? I get it. I'm irresistible.",cb:[]},
{n:"Neon",s:"Ne",num:10,e:"✨",f:"noble",p:"Night lighter",fact:"I glow in the dark!",story:"Bright signs at night? My show. Pick any color. I light up the whole street.",l1:1,rv:"Want to see me glow? Take a night drive.",cb:[]},
{n:"Argon",s:"Ar",num:18,e:"💡",f:"noble",p:"Shy protector",fact:"I hide in lightbulbs.",story:"Quietly keeping the light going inside every bulb. Don't mind me. Just doing my thing.",l1:1,rv:"Oh... you noticed me? I was trying to be invisible.",cb:[]},
// L2: 98 more (top 15 enriched with combos+revisits)
{n:"Lithium",s:"Li",num:3,e:"🔋",f:"explosion",fact:"I power batteries!",story:"Every time the iPad charges, I store all that energy inside.",rv:"Charge me up! I'm ready to go again.",cb:[{w:"Oxygen",r:"Lithium Oxide 🔋",eq:"Li₂O"}]},
{n:"Beryllium",s:"Be",num:4,e:"💚",f:"earth",fact:"I make emeralds green!",story:"Gorgeous green gems? I make them green. Hiding inside every emerald."},
{n:"Boron",s:"B",num:5,e:"🧹",f:"halfhalf",fact:"I clean your clothes!",story:"In laundry soap fighting stains. Also in some slime recipes!"},
{n:"Fluorine",s:"F",num:9,e:"😁",f:"saltmaker",fact:"I protect your teeth!",story:"In toothpaste fighting sugar bugs and making teeth tough.",rv:"Brush your teeth yet today? I'll be waiting!"},
{n:"Magnesium",s:"Mg",num:12,e:"🎆",f:"earth",fact:"I make bright flashes!",story:"Fireworks and sparklers use me for that dazzling white burst."},
{n:"Phosphorus",s:"P",num:15,e:"🕯️",f:"lifemaker",fact:"I glow AND I'm in DNA!",story:"Strike a match? That's me! Also hiding in bones and DNA."},
{n:"Scandium",s:"Sc",num:21,e:"🏟️",f:"warrior",fact:"Stadium lights need me!",story:"Super bright stadium lights at the ballpark? I help them shine."},
{n:"Vanadium",s:"V",num:23,e:"🔧",f:"warrior",fact:"I toughen up steel!",story:"Tools, springs, jet engines. I mix into steel and make it way stronger."},
{n:"Chromium",s:"Cr",num:24,e:"🪩",f:"warrior",fact:"I make things shiny!",story:"Chrome bumpers, stainless steel. That mirror shine is all me."},
{n:"Manganese",s:"Mn",num:25,e:"🥫",f:"warrior",fact:"I stop rust!",story:"Without me, train tracks crumble and cans fall apart."},
{n:"Cobalt",s:"Co",num:27,e:"🔵",f:"warrior",fact:"I paint the best blue!",story:"That deep gorgeous blue in paintings? My color for thousands of years."},
{n:"Zinc",s:"Zn",num:30,e:"🛡️",f:"warrior",fact:"I help cuts heal!",story:"Scrapes and cuts? I help the body fix them. Also in sunscreen!",rv:"Got any scrapes? I'm on the job."},
{n:"Gallium",s:"Ga",num:31,e:"🫠",f:"shifter",fact:"I melt in your hand!",story:"Hold me and I turn to liquid metal puddle. How cool is that?",rv:"Want to melt me again? I love that trick."},
{n:"Germanium",s:"Ge",num:32,e:"🔌",f:"halfhalf",fact:"First computer chip!",story:"Before Silicon took over, I was the star of electronics."},
{n:"Arsenic",s:"As",num:33,e:"☠️",f:"halfhalf",fact:"Famous sneaky poison!",story:"Mystery books love me. But I also make green fireworks!"},
{n:"Selenium",s:"Se",num:34,e:"🥜",f:"lifemaker",fact:"I hide in Brazil nuts!",story:"Your body needs tiny bits of me to stay healthy and strong."},
{n:"Bromine",s:"Br",num:35,e:"🟫",f:"saltmaker",fact:"I'm liquid AND stinky!",story:"My name literally means stench in Greek. I earned it.",rv:"Yeah, I stink. At least I own it."},
{n:"Krypton",s:"Kr",num:36,e:"🦸",f:"noble",fact:"Not Superman's planet!",story:"I'm real! I glow bright white. Superman's planet just borrowed my cool name.",rv:"No, I can't give you superpowers. Stop asking.",cb:[{w:"Electricity",r:"White Light ⚡",eq:"Kr → glow"}]},
{n:"Rubidium",s:"Rb",num:37,e:"🕰️",f:"explosion",fact:"I keep perfect time!",story:"GPS satellites use clocks made with me to know exactly where {name} is."},
{n:"Strontium",s:"Sr",num:38,e:"🎇",f:"earth",fact:"Red fireworks are me!",story:"That deep red in fireworks on the Fourth of July? I light up the sky!"},
{n:"Yttrium",s:"Y",num:39,e:"📺",f:"warrior",fact:"I make screens glow red!",story:"That red on the TV? I help create it in every show {name} watches."},
{n:"Zirconium",s:"Zr",num:40,e:"💍",f:"warrior",fact:"I look like diamonds!",story:"Sparkly gems that look like diamonds? Some are made from me!"},
{n:"Niobium",s:"Nb",num:41,e:"🚀",f:"warrior",fact:"I build rocket engines!",story:"I handle insane heat without melting. Rockets need me."},
{n:"Molybdenum",s:"Mo",num:42,e:"⚔️",f:"warrior",fact:"I make steel unbreakable!",story:"The strongest steel in the world has me mixed in."},
{n:"Technetium",s:"Tc",num:43,e:"⚗️",f:"warrior",fact:"First lab-made element!",story:"Scientists created me! I help doctors take pictures inside bodies."},
{n:"Ruthenium",s:"Ru",num:44,e:"💽",f:"warrior",fact:"I store computer data!",story:"Hard drives use me to remember files and photos."},
{n:"Rhodium",s:"Rh",num:45,e:"🏆",f:"warrior",fact:"Pricier than gold!",story:"I'm rare, shiny, and super valuable. Cars need me to clean exhaust."},
{n:"Palladium",s:"Pd",num:46,e:"🚗",f:"warrior",fact:"I clean car exhaust!",story:"Inside catalytic converters, turning bad air into cleaner air."},
{n:"Cadmium",s:"Cd",num:48,e:"🎨",f:"warrior",fact:"Bright yellow paint!",story:"Famous painters used me for the brightest yellows that pop."},
{n:"Indium",s:"In",num:49,e:"📱",f:"shifter",fact:"Touchscreens need me!",story:"Every tap on the iPad? I'm why the screen responds."},
{n:"Tin",s:"Sn",num:50,e:"🥫",f:"shifter",fact:"I keep food fresh!",story:"Cans of soup? I coat them to keep food safe and yummy."},
{n:"Antimony",s:"Sb",num:51,e:"🔥",f:"halfhalf",fact:"I stop fires!",story:"Mixed into materials to keep fires from spreading. Safety hero!"},
{n:"Tellurium",s:"Te",num:52,e:"🧄",f:"halfhalf",fact:"Garlic breath for weeks!",story:"Touch me and your breath smells like garlic forever. Sorry!",rv:"Still have garlic breath? That might be me."},
{n:"Iodine",s:"I",num:53,e:"🧂",f:"saltmaker",fact:"I turn purple when hot!",story:"Brown stuff on scrapes? Me! Heat me up and I turn gorgeous purple."},
{n:"Xenon",s:"Xe",num:54,e:"🔦",f:"noble",fact:"Brightest headlights!",story:"Super bright blue-white car headlights? That's me shining."},
{n:"Cesium",s:"Cs",num:55,e:"⏱️",f:"explosion",fact:"I define one second!",story:"Scientists use me to measure what one second actually is."},
{n:"Barium",s:"Ba",num:56,e:"🟢",f:"earth",fact:"Green fireworks!",story:"Doctors also use me to see inside tummies with special cameras."},
{n:"Lanthanum",s:"La",num:57,e:"🎬",f:"hidden",fact:"Movie lights need me!",story:"Hollywood uses me to light up movie sets super bright."},
{n:"Cerium",s:"Ce",num:58,e:"🔥",f:"hidden",fact:"I spark lighters!",story:"That little wheel making sparks? I create those sparks!"},
{n:"Praseodymium",s:"Pr",num:59,e:"🥽",f:"hidden",fact:"I shield welder eyes!",story:"Green goggles protecting eyes from super hot torches? Me."},
{n:"Neodymium",s:"Nd",num:60,e:"🧲",f:"hidden",fact:"Strongest magnets!",story:"Headphones and speakers have my super-strong magnets inside.",rv:"Put two of my magnets together. Feel that pull? That's me.",cb:[{w:"Iron+Boron",r:"Super Magnet 🧲",eq:"Nd₂Fe₁₄B"}]},
{n:"Promethium",s:"Pm",num:61,e:"🌙",f:"hidden",fact:"I glow in the dark!",story:"Named after the god who stole fire. I glow like tiny fire."},
{n:"Samarium",s:"Sm",num:62,e:"🧲",f:"hidden",fact:"Guitar magnets!",story:"Electric guitars use me to pick up string vibrations."},
{n:"Europium",s:"Eu",num:63,e:"💶",f:"hidden",fact:"I protect real money!",story:"Hidden in bills. UV light reveals me, proving money is real."},
{n:"Gadolinium",s:"Gd",num:64,e:"🏥",f:"hidden",fact:"I help MRI machines!",story:"Doctors use me to see clearer pictures inside bodies."},
{n:"Terbium",s:"Tb",num:65,e:"📺",f:"hidden",fact:"Green on TV screens!",story:"That green color on TV? I help create it."},
{n:"Dysprosium",s:"Dy",num:66,e:"💨",f:"hidden",fact:"My name means hard-to-get!",story:"So hard to find, they named me that. Now I'm in wind turbines."},
{n:"Holmium",s:"Ho",num:67,e:"🧲",f:"hidden",fact:"Mega magnet power!",story:"I create the most powerful magnetic fields of any element."},
{n:"Erbium",s:"Er",num:68,e:"🌐",f:"hidden",fact:"I boost the internet!",story:"Internet signals travel through glass cables. I keep them strong."},
{n:"Thulium",s:"Tm",num:69,e:"📡",f:"hidden",fact:"Rare laser maker!",story:"Doctors use my special lasers for delicate surgeries."},
{n:"Ytterbium",s:"Yb",num:70,e:"⏰",f:"hidden",fact:"Future clock!",story:"Scientists are building the next super-accurate clock with me."},
{n:"Lutetium",s:"Lu",num:71,e:"🔬",f:"hidden",fact:"I fight cancer!",story:"Doctors use me in special treatments. Tiny but mighty."},
{n:"Hafnium",s:"Hf",num:72,e:"⚡",f:"warrior",fact:"Nuclear controller!",story:"Inside power plants, I keep nuclear energy safe and useful."},
{n:"Tantalum",s:"Ta",num:73,e:"📱",f:"warrior",fact:"Inside every phone!",story:"The iPad has me inside, helping electronics work smoothly."},
{n:"Tungsten",s:"W",num:74,e:"💡",f:"warrior",fact:"Highest melting point!",story:"Old lightbulbs had me as the glowing wire. I never melt.",rv:"Go ahead, try to melt me. You can't. Nobody can."},
{n:"Rhenium",s:"Re",num:75,e:"✈️",f:"warrior",fact:"Jet engine survivor!",story:"Inside the hottest part of jet engines, still standing."},
{n:"Osmium",s:"Os",num:76,e:"⚖️",f:"warrior",fact:"Heaviest element!",story:"Hold me and I feel WAY heavier than expected. Heavyweight champ."},
{n:"Iridium",s:"Ir",num:77,e:"☄️",f:"warrior",fact:"Dinosaur detective!",story:"The asteroid that killed the dinosaurs left me behind as the clue. Space detective.",rv:"Still thinking about those dinosaurs? Me too.",cb:[{w:"Asteroid impact",r:"Extinction evidence 🦕",eq:"Ir layer"}]},
{n:"Platinum",s:"Pt",num:78,e:"💎",f:"warrior",fact:"Rarer than gold!",story:"Fanciest rings and watches. I stay perfect forever.",rv:"Yes, I'm fancier than Gold. Don't tell him."},
{n:"Mercury",s:"Hg",num:80,e:"🌡️",f:"warrior",fact:"Liquid metal!",story:"Only metal that's liquid at room temperature. I flow like water but I'm metal. Wild, right?",rv:"Still amazed I'm liquid? Everyone is. It's my best trick.",cb:[{w:"Room temp",r:"Liquid Metal 🌊",eq:"Hg (liquid)"}]},
{n:"Thallium",s:"Tl",num:81,e:"🔍",f:"shifter",fact:"Night vision helper!",story:"Night vision cameras use me to see in pitch darkness."},
{n:"Lead",s:"Pb",num:82,e:"🛡️",f:"shifter",fact:"X-ray blocker!",story:"Heavy lead vests at the doctor? Me, keeping you safe from X-rays."},
{n:"Bismuth",s:"Bi",num:83,e:"🌈",f:"shifter",fact:"Rainbow crystals!",story:"I grow staircase crystals with every rainbow color. Prettiest metal ever!",rv:"Want to see my rainbow stairs again? I'll never get tired of showing them.",cb:[{w:"Crystallization",r:"Rainbow Stairs 🌈",eq:"Bi crystals"}]},
{n:"Polonium",s:"Po",num:84,e:"☢️",f:"shifter",fact:"Discovered by Curie!",story:"Marie Curie named me after Poland. Rare and radioactive."},
{n:"Astatine",s:"At",num:85,e:"👤",f:"saltmaker",fact:"Rarest natural element!",story:"Less than one ounce of me on the whole planet. Ultimate rare find."},
{n:"Radon",s:"Rn",num:86,e:"🏠",f:"noble",fact:"Basement lurker!",story:"Radioactive gas that sneaks into basements. Test your home!"},
{n:"Francium",s:"Fr",num:87,e:"💥",f:"explosion",fact:"Ultra rare exploder!",story:"Only about 30 grams of me exist at any time. Then I vanish."},
{n:"Radium",s:"Ra",num:88,e:"☢️",f:"earth",fact:"I glow by myself!",story:"Marie Curie discovered me. Old clocks had me to glow at night."},
{n:"Actinium",s:"Ac",num:89,e:"✨",f:"radioactive",fact:"Blue glow!",story:"Put me in a dark room and I shine pale blue. Pure energy."},
{n:"Thorium",s:"Th",num:90,e:"⚡",f:"radioactive",fact:"Named after THOR!",story:"The god of thunder gave me his name! Scientists think I could power clean energy plants someday.",rv:"THOR! Say it louder! I love my name!",cb:[{w:"Nuclear reactor",r:"Clean Energy ⚡",eq:"Th fuel"}]},
{n:"Protactinium",s:"Pa",num:91,e:"🔗",f:"radioactive",fact:"I become Actinium!",story:"I slowly transform over time. Like a very slow metamorphosis."},
{n:"Uranium",s:"U",num:92,e:"☢️",f:"radioactive",fact:"I power whole cities!",story:"One tiny piece of me has more energy than tons and tons of coal. I am pure, concentrated power.",rv:"One little piece of me powers a whole city. Let that sink in.",cb:[{w:"Fission",r:"Nuclear Energy ⚡",eq:"U → energy"},{w:"Time",r:"Lead (eventually) ⏳",eq:"U → Pb"}]},
{n:"Neptunium",s:"Np",num:93,e:"🔵",f:"radioactive",fact:"Named after Neptune!",story:"Like Neptune after Uranus in space, I follow Uranium on the table."},
{n:"Plutonium",s:"Pu",num:94,e:"💣",f:"radioactive",fact:"Planet-level power!",story:"Named after dwarf planet Pluto. I pack incredible, world-changing power in a tiny, tiny space.",rv:"Careful. I'm the most powerful thing in this whole app.",cb:[{w:"Fission",r:"Massive Energy 💥",eq:"Pu → energy"}]},
{n:"Americium",s:"Am",num:95,e:"🚨",f:"radioactive",fact:"In smoke detectors!",story:"That smoke detector on the ceiling? A tiny bit of me is inside, watching for smoke 24/7.",rv:"Beep beep! Just checking. I never sleep."},
{n:"Curium",s:"Cm",num:96,e:"👩‍🔬",f:"radioactive",fact:"Named after Curie!",story:"Marie Curie was one of the greatest scientists ever."},
{n:"Berkelium",s:"Bk",num:97,e:"🐻",f:"radioactive",fact:"Made in Berkeley!",story:"University of California created more elements than almost anywhere."},
{n:"Californium",s:"Cf",num:98,e:"🌉",f:"radioactive",fact:"Underground scanner!",story:"I scan deep underground to find gold and oil. Metal detector on steroids."},
{n:"Einsteinium",s:"Es",num:99,e:"🧠",f:"radioactive",fact:"Einstein's element!",story:"Named after the most famous scientist. I carry genius."},
{n:"Fermium",s:"Fm",num:100,e:"⚛️",f:"radioactive",fact:"Number 100!",story:"Found in nuclear test dust. The big one-zero-zero."},
{n:"Mendelevium",s:"Md",num:101,e:"📋",f:"radioactive",fact:"Table maker's tribute!",story:"Named after the man who invented the periodic table itself."},
{n:"Nobelium",s:"No",num:102,e:"🏅",f:"radioactive",fact:"Nobel Prize element!",story:"The biggest award in science gave me my name."},
{n:"Lawrencium",s:"Lr",num:103,e:"🔬",f:"radioactive",fact:"Lab legend!",story:"Ernest Lawrence built the atom smasher that helped discover me."},
{n:"Rutherfordium",s:"Rf",num:104,e:"🔬",f:"warrior",fact:"Smashed into existence!",story:"Made by crashing atoms together at incredible speed."},
{n:"Dubnium",s:"Db",num:105,e:"🔬",f:"warrior",fact:"Born in Russia!",story:"Named after Dubna, the city where atom-smashing geniuses work."},
{n:"Seaborgium",s:"Sg",num:106,e:"🔬",f:"warrior",fact:"Ten elements guy!",story:"Named after Glenn Seaborg, who discovered TEN elements."},
{n:"Bohrium",s:"Bh",num:107,e:"🔬",f:"warrior",fact:"Gone in a flash!",story:"I exist for a tiny fraction of a second, then vanish."},
{n:"Hassium",s:"Hs",num:108,e:"🔬",f:"warrior",fact:"German-made!",story:"Named after Hesse, Germany. Super heavy, super rare."},
{n:"Meitnerium",s:"Mt",num:109,e:"👩‍🔬",f:"warrior",fact:"Named for a hero!",story:"Lise Meitner helped discover nuclear fission. My hero!"},
{n:"Darmstadtium",s:"Ds",num:110,e:"🔬",f:"warrior",fact:"Blink and I'm gone!",story:"I disappear in millionths of a second."},
{n:"Roentgenium",s:"Rg",num:111,e:"📷",f:"warrior",fact:"X-ray tribute!",story:"Named after the man who discovered X-rays."},
{n:"Copernicium",s:"Cn",num:112,e:"🌍",f:"warrior",fact:"Earth orbits the Sun!",story:"Copernicus figured that out. I carry his name."},
{n:"Nihonium",s:"Nh",num:113,e:"🇯🇵",f:"shifter",fact:"Japan's element!",story:"Japanese scientists worked super hard to create me."},
{n:"Flerovium",s:"Fl",num:114,e:"🔬",f:"shifter",fact:"Russian creation!",story:"Only a few atoms of me have ever existed."},
{n:"Moscovium",s:"Mc",num:115,e:"🔬",f:"shifter",fact:"Moscow's element!",story:"One of the newest members of the periodic table."},
{n:"Livermorium",s:"Lv",num:116,e:"🔬",f:"shifter",fact:"California made!",story:"I exist for less than a blink before vanishing."},
{n:"Tennessine",s:"Ts",num:117,e:"🔬",f:"saltmaker",fact:"Tennessee's element!",story:"Scientists at Oak Ridge National Lab helped create me."},
{n:"Oganesson",s:"Og",num:118,e:"🏁",f:"noble",fact:"The FINAL element!",story:"Number 118. The grand finale. The heaviest ever made. I'm the finish line of the periodic table.",rv:"{name}... you did it. Every element. Every power. I am whole again for the first time in a thousand years. I am Eternatus, the Eternal Dragon. And you are my champion.",eLine:"THE FINAL POWER! I AM COMPLETE!"}
];

var EL={};E.forEach(function(el){EL[el.num]=el});

// Periodic table positions [row,col]
var PP={1:[1,1],2:[1,18],3:[2,1],4:[2,2],5:[2,13],6:[2,14],7:[2,15],8:[2,16],9:[2,17],10:[2,18],11:[3,1],12:[3,2],13:[3,13],14:[3,14],15:[3,15],16:[3,16],17:[3,17],18:[3,18],19:[4,1],20:[4,2],21:[4,3],22:[4,4],23:[4,5],24:[4,6],25:[4,7],26:[4,8],27:[4,9],28:[4,10],29:[4,11],30:[4,12],31:[4,13],32:[4,14],33:[4,15],34:[4,16],35:[4,17],36:[4,18],37:[5,1],38:[5,2],39:[5,3],40:[5,4],41:[5,5],42:[5,6],43:[5,7],44:[5,8],45:[5,9],46:[5,10],47:[5,11],48:[5,12],49:[5,13],50:[5,14],51:[5,15],52:[5,16],53:[5,17],54:[5,18],55:[6,1],56:[6,2],72:[6,4],73:[6,5],74:[6,6],75:[6,7],76:[6,8],77:[6,9],78:[6,10],79:[6,11],80:[6,12],81:[6,13],82:[6,14],83:[6,15],84:[6,16],85:[6,17],86:[6,18],87:[7,1],88:[7,2],104:[7,4],105:[7,5],106:[7,6],107:[7,7],108:[7,8],109:[7,9],110:[7,10],111:[7,11],112:[7,12],113:[7,13],114:[7,14],115:[7,15],116:[7,16],117:[7,17],118:[7,18],57:[9,4],58:[9,5],59:[9,6],60:[9,7],61:[9,8],62:[9,9],63:[9,10],64:[9,11],65:[9,12],66:[9,13],67:[9,14],68:[9,15],69:[9,16],70:[9,17],71:[9,18],89:[10,4],90:[10,5],91:[10,6],92:[10,7],93:[10,8],94:[10,9],95:[10,10],96:[10,11],97:[10,12],98:[10,13],99:[10,14],100:[10,15],101:[10,16],102:[10,17],103:[10,18]};

// Column families for Dragon's Map teaching
var COL_FAM={1:'explosion',2:'earth',3:'warrior',4:'warrior',5:'warrior',6:'warrior',7:'warrior',8:'warrior',9:'warrior',10:'warrior',11:'warrior',12:'warrior',13:'shifter',14:'halfhalf',15:'lifemaker',16:'lifemaker',17:'saltmaker',18:'noble'};
var COL_TEACH={1:"Column 1: The Explosion Squad! They all blow up in water.",2:"Column 2: Earth Builders! Strong and steady.",18:"Column 18: The Glow Squad! Loners who never react with anyone.",17:"Column 17: Salt Makers! Fierce and stinky.",14:"Column 14: Half-and-Halfs! Part metal, part not."};
